import fs from 'node:fs/promises';
import path from 'node:path';
import {DatabaseSync} from 'node:sqlite';

import type {BetterAuthOptions} from 'better-auth';
import {getMigrations} from 'better-auth/db/migration';
import {
  type DBAdapter,
  type DBAdapterInstance,
  type DBAdapterSchemaCreation,
  type DBTransactionAdapter,
} from 'better-auth/adapters';

import type {SqlfuConfig, SqlfuProjectConfig} from './types.js';

const adapterId = 'sqlfu';
const adapterName = 'sqlfu Better Auth adapter';
const managedSectionName = 'sqlfu:better-auth';
const beginMarker = `-- #region ${managedSectionName}`;
const endMarker = `-- #endregion ${managedSectionName}`;

export interface SqlfuBetterAuthAdapterInput<Options extends BetterAuthOptions = BetterAuthOptions> {
  sqlfu: SqlfuConfig | SqlfuProjectConfig;
  adapter: DBAdapterInstance<Options>;
  projectRoot?: string;
}

/**
 * Wraps a Better Auth adapter so Better Auth's `auth generate` command updates
 * sqlfu's configured `definitions.sql` instead of asking Better Auth to own
 * migration files or database diffs.
 *
 * This adapter is currently intended and tested for schema generation. Runtime
 * create/read/update/delete methods are delegated to the adapter you pass in,
 * but sqlfu does not currently claim deeper runtime adapter coverage beyond that
 * delegation. After running `auth generate`, keep sqlfu as the migration owner
 * by running `sqlfu draft` and `sqlfu migrate`.
 *
 * The Better Auth schema SQL is generated by running Better Auth's Kysely
 * migration compiler against an empty in-memory SQLite database. That keeps
 * sqlfu aligned with Better Auth's own SQLite SQL output, but currently means
 * wrapped adapter naming options such as `usePlural` are not part of the tested
 * schema-generation contract.
 */
export function sqlfuBetterAuthAdapter<Options extends BetterAuthOptions = BetterAuthOptions>(
  input: SqlfuBetterAuthAdapterInput<Options>,
): DBAdapterInstance<Options> {
  return (options) => wrapAdapter(input, input.adapter(options));
}

function wrapAdapter<Options extends BetterAuthOptions>(
  input: SqlfuBetterAuthAdapterInput<Options>,
  base: DBAdapter<Options>,
): DBAdapter<Options> {
  return {
    ...base,
    id: adapterId,
    options: {
      ...base.options,
      adapterConfig: {
        ...base.options?.adapterConfig,
        adapterId,
        adapterName,
      },
    },
    async transaction(callback) {
      return base.transaction(async (tx) => callback(wrapTransactionAdapter(input, tx)));
    },
    async createSchema(options, file) {
      return createSqlfuBetterAuthSchema(input, options, file);
    },
  };
}

function wrapTransactionAdapter<Options extends BetterAuthOptions>(
  input: SqlfuBetterAuthAdapterInput<Options>,
  base: DBTransactionAdapter<Options>,
): DBTransactionAdapter<Options> {
  return {
    ...base,
    id: adapterId,
    options: {
      ...base.options,
      adapterConfig: {
        ...base.options?.adapterConfig,
        adapterId,
        adapterName,
      },
    },
    async createSchema(options, file) {
      return createSqlfuBetterAuthSchema(input, options, file);
    },
  };
}

async function createSqlfuBetterAuthSchema<Options extends BetterAuthOptions>(
  input: SqlfuBetterAuthAdapterInput<Options>,
  options: Options,
  file: string | undefined,
): Promise<DBAdapterSchemaCreation> {
  const projectRoot = resolveProjectRoot(input);
  const definitionsPath = path.resolve(projectRoot, input.sqlfu.definitions);
  const requestedPath = file ? path.resolve(projectRoot, file) : definitionsPath;

  if (requestedPath !== definitionsPath) {
    throw new Error(
      [
        `sqlfuBetterAuthAdapter can only generate ${path.relative(projectRoot, definitionsPath)}.`,
        `Received output file ${file || '<none>'}.`,
        'Run Better Auth generate with the configured sqlfu definitions file, or omit --output.',
      ].join('\n'),
    );
  }

  const currentDefinitionsSql = await readExistingDefinitions(definitionsPath);
  const generatedSection = await renderBetterAuthManagedSection(options);
  const nextDefinitionsSql = replaceBetterAuthManagedSection(currentDefinitionsSql, generatedSection);

  return {
    code: nextDefinitionsSql === currentDefinitionsSql ? '' : nextDefinitionsSql,
    path: outputPathForBetterAuthCli(file, definitionsPath),
    overwrite: true,
  };
}

function resolveProjectRoot<Options extends BetterAuthOptions>(input: SqlfuBetterAuthAdapterInput<Options>) {
  if ('projectRoot' in input.sqlfu) return input.sqlfu.projectRoot;
  return input.projectRoot || process.cwd();
}

async function readExistingDefinitions(definitionsPath: string): Promise<string> {
  try {
    return await fs.readFile(definitionsPath, 'utf8');
  } catch (error) {
    if (error instanceof Error && 'code' in error && error.code === 'ENOENT') {
      return '';
    }
    throw error;
  }
}

function outputPathForBetterAuthCli(file: string | undefined, definitionsPath: string) {
  if (file && !path.isAbsolute(file)) return file;
  return path.relative(process.cwd(), definitionsPath);
}

async function renderBetterAuthManagedSection(options: BetterAuthOptions) {
  const sql = await renderBetterAuthSchemaSql(options);
  return [
    beginMarker,
    '-- generated by Better Auth through sqlfuBetterAuthAdapter; edit Better Auth config instead',
    sql.trim(),
    endMarker,
  ]
    .filter(Boolean)
    .join('\n');
}

function replaceBetterAuthManagedSection(currentDefinitionsSql: string, generatedSection: string) {
  if (!currentDefinitionsSql.trim()) {
    return `${generatedSection}\n`;
  }

  const beginIndexes = markerIndexes(currentDefinitionsSql, beginMarker);
  const endIndexes = markerIndexes(currentDefinitionsSql, endMarker);

  if (beginIndexes.length === 0 && endIndexes.length === 0) {
    throw new Error(
      [
        'definitions.sql already contains application SQL but no sqlfu Better Auth managed section.',
        'Add the managed section markers before running Better Auth generate:',
        '',
        beginMarker,
        endMarker,
      ].join('\n'),
    );
  }
  if (beginIndexes.length !== 1 || endIndexes.length !== 1) {
    throw new Error('definitions.sql must contain exactly one sqlfu Better Auth managed section.');
  }
  const beginIndex = beginIndexes[0]!;
  const endIndex = endIndexes[0]!;
  if (endIndex < beginIndex) {
    throw new Error('definitions.sql has a malformed sqlfu Better Auth managed section.');
  }

  return [
    currentDefinitionsSql.slice(0, beginIndex),
    generatedSection,
    currentDefinitionsSql.slice(endIndex + endMarker.length),
  ].join('');
}

function markerIndexes(value: string, marker: string) {
  const indexes: number[] = [];
  let cursor = 0;
  while (cursor < value.length) {
    const index = value.indexOf(marker, cursor);
    if (index === -1) break;
    indexes.push(index);
    cursor = index + marker.length;
  }
  return indexes;
}

async function renderBetterAuthSchemaSql(options: BetterAuthOptions) {
  const database = new DatabaseSync(':memory:');
  try {
    const {compileMigrations} = await getMigrations({
      ...options,
      database,
    });
    const sql = await compileMigrations();
    return sql.trim() === ';' ? '' : sql;
  } finally {
    database.close();
  }
}
