import fs from 'node:fs/promises';
import path from 'node:path';
import {DatabaseSync} from 'node:sqlite';

import type {BetterAuthOptions} from 'better-auth';
import {getMigrations} from 'better-auth/db/migration';
import {
  type DBAdapter,
  type DBAdapterInstance,
  type DBAdapterSchemaCreation,
  type DBTransactionAdapter,
} from 'better-auth/adapters';

import {formatSqlFileContents} from './formatter.js';
import {loadProjectConfig} from './node/config.js';
import type {SqlfuConfig, SqlfuProjectConfig} from './types.js';

const adapterId = 'sqlfu';
const adapterName = 'sqlfu Better Auth adapter';
const managedSectionName = 'sqlfu:better-auth';
const beginMarker = `-- #region ${managedSectionName}`;
const endMarker = `-- #endregion ${managedSectionName}`;

export interface SqlfuBetterAuthAdapterInput<Options extends BetterAuthOptions = BetterAuthOptions> {
  sqlfu?: SqlfuConfig | SqlfuProjectConfig;
  adapter?: DBAdapterInstance<Options>;
  projectRoot?: string;
  configPath?: string;
}

/**
 * Wraps a Better Auth adapter so Better Auth's `auth generate` command updates
 * sqlfu's configured `definitions.sql` instead of asking Better Auth to own
 * migration files or database diffs.
 *
 * This adapter is currently intended and tested for schema generation. If you
 * call `sqlfuBetterAuthAdapter()` with no input, it resolves `sqlfu.config.*`
 * from the current working directory and installs schema-only runtime methods
 * that throw if used outside `auth generate`. If you pass `adapter`, runtime
 * create/read/update/delete methods are delegated to that adapter, but sqlfu
 * does not currently claim deeper runtime adapter coverage beyond that
 * delegation. After running `auth generate`, keep sqlfu as the migration owner
 * by running `sqlfu draft` and `sqlfu migrate`.
 *
 * The Better Auth schema SQL is generated by running Better Auth's Kysely
 * migration compiler against an empty in-memory SQLite database. That keeps
 * sqlfu aligned with Better Auth's own SQLite SQL output, but currently means
 * wrapped adapter naming options such as `usePlural` are not part of the tested
 * schema-generation contract. The generated Better Auth section is formatted
 * with sqlfu's formatter. On the first run for a nonempty definitions file, the
 * adapter appends the managed section when the combined desired schema applies
 * cleanly to a scratch SQLite database.
 */
export function sqlfuBetterAuthAdapter<Options extends BetterAuthOptions = BetterAuthOptions>(
  input: SqlfuBetterAuthAdapterInput<Options> = {},
): DBAdapterInstance<Options> {
  return (options) => wrapAdapter(input, input.adapter ? input.adapter(options) : createSchemaOnlyAdapter<Options>());
}

function wrapAdapter<Options extends BetterAuthOptions>(
  input: SqlfuBetterAuthAdapterInput<Options>,
  base: DBAdapter<Options>,
): DBAdapter<Options> {
  return {
    ...base,
    id: adapterId,
    options: {
      ...base.options,
      adapterConfig: {
        ...base.options?.adapterConfig,
        adapterId,
        adapterName,
      },
    },
    async transaction(callback) {
      return base.transaction(async (tx) => callback(wrapTransactionAdapter(input, tx)));
    },
    async createSchema(options, file) {
      return createSqlfuBetterAuthSchema(input, options, file);
    },
  };
}

function createSchemaOnlyAdapter<Options extends BetterAuthOptions>(): DBAdapter<Options> {
  return {
    id: adapterId,
    options: {
      adapterConfig: {
        adapterId,
        adapterName,
      },
    },
    create: unsupportedRuntimeMethod,
    findOne: unsupportedRuntimeMethod,
    findMany: unsupportedRuntimeMethod,
    count: unsupportedRuntimeMethod,
    update: unsupportedRuntimeMethod,
    updateMany: unsupportedRuntimeMethod,
    delete: unsupportedRuntimeMethod,
    deleteMany: unsupportedRuntimeMethod,
    async transaction(callback) {
      return callback(createSchemaOnlyTransactionAdapter<Options>());
    },
  };
}

function createSchemaOnlyTransactionAdapter<Options extends BetterAuthOptions>(): DBTransactionAdapter<Options> {
  return {
    id: adapterId,
    options: {
      adapterConfig: {
        adapterId,
        adapterName,
      },
    },
    create: unsupportedRuntimeMethod,
    findOne: unsupportedRuntimeMethod,
    findMany: unsupportedRuntimeMethod,
    count: unsupportedRuntimeMethod,
    update: unsupportedRuntimeMethod,
    updateMany: unsupportedRuntimeMethod,
    delete: unsupportedRuntimeMethod,
    deleteMany: unsupportedRuntimeMethod,
  };
}

async function unsupportedRuntimeMethod(): Promise<never> {
  throw new Error(
    'sqlfuBetterAuthAdapter() without an underlying Better Auth adapter is only intended for `auth generate`. ' +
      'Pass `adapter` to delegate Better Auth runtime database operations.',
  );
}

function wrapTransactionAdapter<Options extends BetterAuthOptions>(
  input: SqlfuBetterAuthAdapterInput<Options>,
  base: DBTransactionAdapter<Options>,
): DBTransactionAdapter<Options> {
  return {
    ...base,
    id: adapterId,
    options: {
      ...base.options,
      adapterConfig: {
        ...base.options?.adapterConfig,
        adapterId,
        adapterName,
      },
    },
    async createSchema(options, file) {
      return createSqlfuBetterAuthSchema(input, options, file);
    },
  };
}

async function createSqlfuBetterAuthSchema<Options extends BetterAuthOptions>(
  input: SqlfuBetterAuthAdapterInput<Options>,
  options: Options,
  file: string | undefined,
): Promise<DBAdapterSchemaCreation> {
  const sqlfuConfig = await resolveSqlfuConfig(input);
  const projectRoot = resolveProjectRoot(input, sqlfuConfig);
  const definitionsPath = path.resolve(projectRoot, sqlfuConfig.definitions);
  const requestedPath = file ? path.resolve(projectRoot, file) : definitionsPath;

  if (requestedPath !== definitionsPath) {
    throw new Error(
      [
        `sqlfuBetterAuthAdapter can only generate ${path.relative(projectRoot, definitionsPath)}.`,
        `Received output file ${file || '<none>'}.`,
        'Run Better Auth generate with the configured sqlfu definitions file, or omit --output.',
      ].join('\n'),
    );
  }

  const currentDefinitionsSql = await readExistingDefinitions(definitionsPath);
  const generatedSection = await renderBetterAuthManagedSection(options);
  const nextDefinitionsSql = replaceBetterAuthManagedSection(currentDefinitionsSql, generatedSection);

  return {
    code: nextDefinitionsSql === currentDefinitionsSql ? '' : nextDefinitionsSql,
    path: outputPathForBetterAuthCli(file, definitionsPath),
    overwrite: true,
  };
}

async function resolveSqlfuConfig<Options extends BetterAuthOptions>(
  input: SqlfuBetterAuthAdapterInput<Options>,
): Promise<SqlfuConfig | SqlfuProjectConfig> {
  if (input.sqlfu) return input.sqlfu;
  return loadProjectConfig({configPath: input.configPath});
}

function resolveProjectRoot<Options extends BetterAuthOptions>(
  input: SqlfuBetterAuthAdapterInput<Options>,
  sqlfuConfig: SqlfuConfig | SqlfuProjectConfig,
) {
  if ('projectRoot' in sqlfuConfig) return sqlfuConfig.projectRoot;
  return input.projectRoot || process.cwd();
}

async function readExistingDefinitions(definitionsPath: string): Promise<string> {
  try {
    return await fs.readFile(definitionsPath, 'utf8');
  } catch (error) {
    if (error instanceof Error && 'code' in error && error.code === 'ENOENT') {
      return '';
    }
    throw error;
  }
}

function outputPathForBetterAuthCli(file: string | undefined, definitionsPath: string) {
  if (file && !path.isAbsolute(file)) return file;
  return path.relative(process.cwd(), definitionsPath);
}

async function renderBetterAuthManagedSection(options: BetterAuthOptions) {
  const sql = await renderBetterAuthSchemaSql(options);
  const formattedSql = formatSqlFileContents(sql).trim();
  return [
    beginMarker,
    '-- generated by Better Auth through sqlfuBetterAuthAdapter; edit Better Auth config instead',
    formattedSql,
    endMarker,
  ]
    .filter(Boolean)
    .join('\n');
}

function replaceBetterAuthManagedSection(currentDefinitionsSql: string, generatedSection: string) {
  if (!currentDefinitionsSql.trim()) {
    return `${generatedSection}\n`;
  }

  const beginIndexes = markerIndexes(currentDefinitionsSql, beginMarker);
  const endIndexes = markerIndexes(currentDefinitionsSql, endMarker);

  if (beginIndexes.length === 0 && endIndexes.length === 0) {
    const appendedDefinitionsSql = appendBetterAuthManagedSection(currentDefinitionsSql, generatedSection);
    assertDefinitionsSqlAppliesCleanlyBeforeAppend(appendedDefinitionsSql);
    return appendedDefinitionsSql;
  }
  if (beginIndexes.length !== 1 || endIndexes.length !== 1) {
    throw new Error('definitions.sql must contain exactly one sqlfu Better Auth managed section.');
  }
  const beginIndex = beginIndexes[0]!;
  const endIndex = endIndexes[0]!;
  if (endIndex < beginIndex) {
    throw new Error('definitions.sql has a malformed sqlfu Better Auth managed section.');
  }

  return [
    currentDefinitionsSql.slice(0, beginIndex),
    generatedSection,
    currentDefinitionsSql.slice(endIndex + endMarker.length),
  ].join('');
}

function appendBetterAuthManagedSection(currentDefinitionsSql: string, generatedSection: string) {
  const separator = currentDefinitionsSql.endsWith('\n\n') ? '' : currentDefinitionsSql.endsWith('\n') ? '\n' : '\n\n';
  return `${currentDefinitionsSql}${separator}${generatedSection}\n`;
}

function assertDefinitionsSqlAppliesCleanlyBeforeAppend(definitionsSql: string) {
  const database = new DatabaseSync(':memory:');
  try {
    database.exec(definitionsSql);
  } catch (error) {
    throw new Error(
      [
        'could not append sqlfu Better Auth managed section because the combined definitions.sql did not apply to a scratch SQLite database.',
        'Add the managed section markers manually around Better Auth-owned SQL, or fix the conflicting application SQL, then rerun Better Auth generate.',
        '',
        beginMarker,
        endMarker,
        '',
        `SQLite error: ${error instanceof Error ? error.message : String(error)}`,
      ].join('\n'),
    );
  } finally {
    database.close();
  }
}

function markerIndexes(value: string, marker: string) {
  const indexes: number[] = [];
  let cursor = 0;
  while (cursor < value.length) {
    const index = value.indexOf(marker, cursor);
    if (index === -1) break;
    indexes.push(index);
    cursor = index + marker.length;
  }
  return indexes;
}

async function renderBetterAuthSchemaSql(options: BetterAuthOptions) {
  const database = new DatabaseSync(':memory:');
  try {
    const {compileMigrations} = await getMigrations({
      ...options,
      database,
    });
    const sql = await compileMigrations();
    return sql.trim() === ';' ? '' : sql;
  } finally {
    database.close();
  }
}
