export type QuerySourceManifestEntry = {
  sqlFile: string;
  generatedFile: string;
  sourceSql: string;
};

const QUERY_SOURCE_ENTRY_PATTERN =
  /\{\s*sqlFile:\s*("(?:(?:\\.)|[^"\\])*")\s*,\s*generatedFile:\s*("(?:(?:\\.)|[^"\\])*")\s*,\s*sourceSql:\s*("(?:(?:\\.)|[^"\\])*")\s*,?\s*\}/g;

export function queryIdentityFromPath(value: string): string {
  const parts = value
    .split(/[^A-Za-z0-9]+/)
    .filter(Boolean)
    .map((part) => part.toLowerCase());
  if (parts.length === 0) {
    return '';
  }
  return (
    parts[0]! +
    parts
      .slice(1)
      .map((part) => part[0]!.toUpperCase() + part.slice(1))
      .join('')
  );
}

export function generatedWrapperFileForSqlFile(relativeSqlFile: string): string {
  if (!relativeSqlFile.endsWith('.sql')) {
    throw new Error(`Expected a .sql query source path. Got ${JSON.stringify(relativeSqlFile)}.`);
  }
  return `${relativeSqlFile.slice(0, -'.sql'.length)}.sql.ts`;
}

export function generatedWrapperFileForQueryPath(relativePath: string): string {
  return `${relativePath}.sql.ts`;
}

export function querySourceManifestEntry(input: {relativePath: string; sqlContent: string}): QuerySourceManifestEntry {
  return {
    sqlFile: `${input.relativePath}.sql`,
    generatedFile: generatedWrapperFileForQueryPath(input.relativePath),
    sourceSql: input.sqlContent,
  };
}

export function renderQuerySourceManifest(input: {
  entries: QuerySourceManifestEntry[];
  importExtension: '.js' | '.ts';
}): string {
  const sortedEntries = [...input.entries].sort((left, right) =>
    queryPathFromSqlFile(left.sqlFile).localeCompare(queryPathFromSqlFile(right.sqlFile)),
  );
  const lines = [
    `// Generated by \`sqlfu generate\`. Do not edit.`,
    ``,
    ...sortedEntries.map(
      (entry) => `export * from "./${entry.generatedFile.slice(0, -'.ts'.length)}${input.importExtension}";`,
    ),
    ...(sortedEntries.length === 0 ? [] : [``]),
    `export const sqlfuQuerySources = [`,
    ...sortedEntries.map(
      (entry) =>
        `\t{ sqlFile: ${JSON.stringify(entry.sqlFile)}, generatedFile: ${JSON.stringify(entry.generatedFile)}, sourceSql: ${JSON.stringify(entry.sourceSql)} },`,
    ),
    `];`,
    ``,
  ];
  return lines.join('\n');
}

function queryPathFromSqlFile(sqlFile: string): string {
  return sqlFile.endsWith('.sql') ? sqlFile.slice(0, -'.sql'.length) : sqlFile;
}

export function parseQuerySourceManifest(text: string): QuerySourceManifestEntry[] {
  const entries: QuerySourceManifestEntry[] = [];
  for (const match of text.matchAll(QUERY_SOURCE_ENTRY_PATTERN)) {
    const entry = {
      sqlFile: JSON.parse(match[1]!),
      generatedFile: JSON.parse(match[2]!),
      sourceSql: JSON.parse(match[3]!),
    };
    if (typeof entry.sqlFile !== 'string') continue;
    if (typeof entry.generatedFile !== 'string') continue;
    if (typeof entry.sourceSql !== 'string') continue;
    entries.push(entry);
  }
  return entries;
}
