import fs from 'node:fs/promises';
import path from 'node:path';

import dedent from 'dedent';
import {execaCommand} from 'execa';
import {expect, test} from 'vitest';

import {sqlfuBetterAuthAdapter as sqlfuBetterAuthAdapterUnderTest} from '../src/better-auth.js';
import {extractSchema} from '../src/sqlite-text.js';
import {createTempFixtureRoot, writeFixtureFiles} from './fs-fixture.js';
import {createMigrationsFixture} from './migrations/fixture.js';

const packageRoot = path.resolve(path.dirname(import.meta.filename), '..');

declare const betterAuth: typeof import('better-auth').betterAuth;
declare const sqlfuBetterAuthAdapter: typeof import('../src/better-auth.js').sqlfuBetterAuthAdapter;

test('sqlfuBetterAuthAdapter preserves runtime methods and wraps createSchema', async () => {
  await using fixture = await createBetterAuthFixture({
    files: {
      'definitions.sql': '',
    },
  });

  const create = async () => ({id: 'created-user'});
  const baseAdapter = createBaseAdapter({create});
  const adapter = sqlfuBetterAuthAdapterUnderTest({
    sqlfu: {definitions: './definitions.sql', queries: './sql'},
    projectRoot: fixture.root,
    adapter: () => baseAdapter,
  })({});

  expect(adapter).toMatchObject({
    id: 'sqlfu',
    create,
    options: {
      adapterConfig: {
        adapterId: 'sqlfu',
        adapterName: 'sqlfu Better Auth adapter',
      },
    },
  });
  const transactionAdapter = await adapter.transaction(async (tx) => tx);

  const schema = await adapter.createSchema?.({}, 'definitions.sql');

  expect(schema).toMatchObject({
    path: 'definitions.sql',
    overwrite: true,
  });
  expect(schema?.code).toContain('-- #region sqlfu:better-auth');
  expect(schema?.code).toContain('create table "user"');
  expect(schema?.code).toContain('"email" text not null unique');
  expect(schema?.code).toContain('-- #endregion sqlfu:better-auth');
  expect(transactionAdapter).toMatchObject({
    id: 'sqlfu',
    options: {
      adapterConfig: {
        adapterId: 'sqlfu',
        adapterName: 'sqlfu Better Auth adapter',
      },
    },
  });
});

test('createSchema preserves application SQL outside the managed Better Auth section', async () => {
  await using fixture = await createBetterAuthFixture({
    files: {
      'definitions.sql': dedent`
        create table "posts" (
          "id" integer primary key not null,
          "slug" text not null unique
        );

        -- #region sqlfu:better-auth
        create table "obsolete_auth_table" ("id" text primary key not null);
        -- #endregion sqlfu:better-auth

        create table "comments" (
          "id" integer primary key not null,
          "postId" integer not null references "posts" ("id") on delete cascade
        );
      `,
    },
  });

  const schema = await createAdapterForFixture(fixture).createSchema?.({}, 'definitions.sql');

  expect(schema?.code).toMatch(/^create table "posts"/);
  expect(schema?.code).toContain('create table "comments"');
  expect(schema?.code).toContain('create table "user"');
  expect(schema?.code).not.toContain('obsolete_auth_table');
  expect(schema?.code).toMatch(
    /-- #region sqlfu:better-auth\n-- generated by Better Auth through sqlfuBetterAuthAdapter; edit Better Auth config instead\ncreate table "user"/,
  );
});

test('createSchema formats generated Better Auth SQL by default', async () => {
  await using fixture = await createBetterAuthFixture({
    files: {
      'definitions.sql': '',
    },
  });

  const schema = await createAdapterForFixture(fixture).createSchema?.({}, 'definitions.sql');

  expect(schema?.code).toContain(dedent`
    create table "user" (
      "id" text not null primary key,
  `);
  expect(schema?.code).not.toContain('create table "user" ("id" text not null primary key');
});

test('createSchema returns empty code when definitions are already up to date', async () => {
  await using fixture = await createBetterAuthFixture({
    files: {
      'definitions.sql': '',
    },
  });
  const adapter = createAdapterForFixture(fixture);
  const firstSchema = await adapter.createSchema?.({}, 'definitions.sql');
  await fixture.writeText('definitions.sql', firstSchema!.code);

  const secondSchema = await adapter.createSchema?.({}, 'definitions.sql');

  expect(secondSchema).toMatchObject({
    code: '',
    path: 'definitions.sql',
    overwrite: true,
  });
});

test('createSchema rejects an output file that is not the configured definitions file', async () => {
  await using fixture = await createBetterAuthFixture({
    files: {
      'definitions.sql': '',
    },
  });

  await expect(createAdapterForFixture(fixture).createSchema?.({}, 'auth-schema.sql')).rejects.toThrow(
    /can only generate definitions\.sql[\s\S]*auth-schema\.sql/,
  );
});

test('createSchema appends a managed section to nonempty definitions when the combined schema applies cleanly', async () => {
  await using fixture = await createBetterAuthFixture({
    files: {
      'definitions.sql': 'create table someotherthing(id int, name text);\n',
    },
  });

  const schema = await createAdapterForFixture(fixture).createSchema?.({}, 'definitions.sql');

  expect(schema?.code).toMatch(/^create table someotherthing\(id int, name text\);\n\n-- #region sqlfu:better-auth/);
  expect(schema?.code).toContain(dedent`
    create table "user" (
      "id" text not null primary key,
  `);
});

test('createSchema rejects first-time append when the combined schema cannot apply cleanly', async () => {
  await using fixture = await createBetterAuthFixture({
    files: {
      'definitions.sql': 'create table "user" ("id" integer primary key not null);\n',
    },
  });

  await expect(createAdapterForFixture(fixture).createSchema?.({}, 'definitions.sql')).rejects.toThrow(
    /could not append sqlfu Better Auth managed section[\s\S]*scratch SQLite database/,
  );
});

test('createSchema rejects malformed Better Auth fences', async () => {
  const cases = [
    {
      name: 'dangling begin',
      definitionsSql: dedent`
        create table "posts" ("id" integer primary key not null);

        -- #region sqlfu:better-auth
        create table "user" ("id" text primary key not null);
      `,
      message: /exactly one sqlfu Better Auth managed section/,
    },
    {
      name: 'multiple sections',
      definitionsSql: dedent`
        -- #region sqlfu:better-auth
        create table "user" ("id" text primary key not null);
        -- #endregion sqlfu:better-auth
        -- #region sqlfu:better-auth
        create table "session" ("id" text primary key not null);
        -- #endregion sqlfu:better-auth
      `,
      message: /exactly one sqlfu Better Auth managed section/,
    },
    {
      name: 'end before begin',
      definitionsSql: dedent`
        -- #endregion sqlfu:better-auth
        create table "posts" ("id" integer primary key not null);
        -- #region sqlfu:better-auth
      `,
      message: /malformed sqlfu Better Auth managed section/,
    },
  ];

  for (const testCase of cases) {
    await using fixture = await createBetterAuthFixture({
      files: {
        'definitions.sql': testCase.definitionsSql,
      },
    });

    await expect(createAdapterForFixture(fixture).createSchema?.({}, 'definitions.sql'), testCase.name).rejects.toThrow(
      testCase.message,
    );
  }
});

test('createSchema uses integer foreign keys when Better Auth is configured for serial ids', async () => {
  await using fixture = await createBetterAuthFixture({
    files: {
      'definitions.sql': '',
    },
  });

  const schema = await createAdapterForFixture(fixture).createSchema?.(
    {
      advanced: {
        database: {
          generateId: 'serial',
        },
      },
    } as any,
    'definitions.sql',
  );

  expect(schema?.code).toContain('"id" integer not null primary key');
  expect(schema?.code).toContain('"userId" integer not null references "user" ("id") on delete cascade');
});

test('createSchema uses Better Auth scratch database output instead of wrapped adapter table naming config', async () => {
  await using fixture = await createBetterAuthFixture({
    files: {
      'definitions.sql': '',
    },
  });
  const adapter = sqlfuBetterAuthAdapterUnderTest({
    sqlfu: {definitions: './definitions.sql', queries: './sql'},
    projectRoot: fixture.root,
    adapter: () =>
      createBaseAdapter({
        options: {
          adapterConfig: {
            adapterId: 'kysely',
            adapterName: 'Kysely Adapter',
            usePlural: true,
          },
        },
      }),
  })({});

  const schema = await adapter.createSchema?.({}, 'definitions.sql');

  expect(schema?.code).toContain('create table "user"');
  expect(schema?.code).toContain('create table "session"');
  expect(schema?.code).toContain('"userId" text not null references "user" ("id") on delete cascade');
  expect(schema?.code).not.toContain('create table "users"');
});

test('generated Better Auth definitions can feed sqlfu draft and migrate', async () => {
  await using authFixture = await createBetterAuthFixture({
    files: {
      'definitions.sql': '',
    },
  });
  const schema = await createAdapterForFixture(authFixture).createSchema?.({}, 'definitions.sql');
  await using sqlfuFixture = await createMigrationsFixture('better-auth-adapter-sqlfu-workflow', {
    desiredSchema: dedent`
      create table "posts" ("id" integer primary key not null);

      ${schema!.code}
    `,
  });

  await sqlfuFixture.api.draft({name: 'better auth schema'});
  await sqlfuFixture.api.migrate();

  expect(await sqlfuFixture.listMigrationFiles()).toEqual([
    'migrations/2026-04-10T00.00.00.000Z_better_auth_schema.sql',
  ]);
  expect(await extractSchema(sqlfuFixture.db, 'main', {excludedTables: ['sqlfu_migrations']})).toContain(
    'create table user',
  );
});

test('createBetterAuthFixture runs auth generate and can reconfigure auth.ts', async () => {
  await using fixture = await createBetterAuthFixture(() => {
    return betterAuth({
      database: sqlfuBetterAuthAdapter(),
      user: {
        additionalFields: {
          role: {
            type: 'string',
            required: false,
            fieldName: 'role',
          },
        },
      },
    });
  });

  await fixture.exec('auth generate --output definitions.sql --yes');

  const firstDefinitionsSql = await fixture.readText('definitions.sql');
  expect(firstDefinitionsSql).toContain('"role" text');

  await fixture.reconfigure(() => {
    return betterAuth({
      database: sqlfuBetterAuthAdapter(),
      user: {
        additionalFields: {
          handle: {
            type: 'string',
            required: true,
            unique: true,
            fieldName: 'handle',
          },
        },
      },
    });
  });

  await fixture.exec('auth generate --output definitions.sql --yes');

  const secondDefinitionsSql = await fixture.readText('definitions.sql');
  expect(secondDefinitionsSql).not.toContain('"role" text');
  expect(secondDefinitionsSql).toContain('"handle" text not null unique');
});

test('auth generate can rely on sqlfu config when no adapter input or output file is passed', async () => {
  await using fixture = await createBetterAuthFixture(() => {
    return betterAuth({
      database: sqlfuBetterAuthAdapter(),
    });
  });

  await fixture.exec('auth generate --yes');

  const definitionsSql = await fixture.readText('definitions.sql');
  expect(definitionsSql).toContain('-- #region sqlfu:better-auth');
  expect(definitionsSql).toContain('create table "user"');
  expect(definitionsSql).toContain('-- #endregion sqlfu:better-auth');
});

async function createBetterAuthFixture(input: BetterAuthFixtureInput) {
  const root = await createTempFixtureRoot('better-auth-adapter');
  const files =
    typeof input === 'function'
      ? {
          'definitions.sql': '',
          'sql/.gitkeep': '',
          'sqlfu.config.js': "export default {definitions: './definitions.sql', queries: './sql'};\n",
        }
      : input.files;
  await writeFixtureFiles(root, {
    'package.json': '{"type":"module"}\n',
    ...files,
  });

  await linkFixtureDependencies(root);

  if (typeof input === 'function') {
    await writeAuthConfig(root, input);
  }

  return {
    root,
    async exec(command: string) {
      return execaCommand(command, {
        cwd: root,
        env: {
          PATH: `${path.join(packageRoot, 'node_modules/.bin')}:${process.env.PATH}`,
          BETTER_AUTH_TELEMETRY_DISABLED: '1',
        },
      });
    },
    async reconfigure(fn: BetterAuthFixtureFactory) {
      await writeAuthConfig(root, fn);
    },
    async readText(relativePath: string) {
      return fs.readFile(path.join(root, relativePath), 'utf8');
    },
    async writeText(relativePath: string, contents: string) {
      await fs.writeFile(path.join(root, relativePath), contents);
    },
    async [Symbol.asyncDispose]() {
      await fs.rm(root, {recursive: true, force: true});
    },
  };
}

type BetterAuthFixtureFactory = () => unknown;
type BetterAuthFixtureInput = BetterAuthFixtureFactory | {files: Record<string, string>};

async function linkFixtureDependencies(root: string) {
  const nodeModules = path.join(root, 'node_modules');
  await fs.mkdir(nodeModules, {recursive: true});
  await fs.symlink(packageRoot, path.join(nodeModules, 'sqlfu'), 'dir');
  await fs.symlink(path.join(packageRoot, 'node_modules/better-auth'), path.join(nodeModules, 'better-auth'), 'dir');
}

async function writeAuthConfig(root: string, fn: BetterAuthFixtureFactory) {
  await fs.writeFile(
    path.join(root, 'auth.ts'),
    dedent`
      import {betterAuth} from 'better-auth';
      import {sqlfuBetterAuthAdapter} from 'sqlfu/better-auth';

      export const auth = (${fn.toString()})();
    `,
  );
}

function createAdapterForFixture(fixture: Awaited<ReturnType<typeof createBetterAuthFixture>>) {
  return sqlfuBetterAuthAdapterUnderTest({
    sqlfu: {definitions: './definitions.sql', queries: './sql'},
    projectRoot: fixture.root,
    adapter: () => createBaseAdapter(),
  })({});
}

function createBaseAdapter(overrides: Record<string, unknown> = {}) {
  const baseAdapter = {
    id: 'kysely',
    async create() {
      return {};
    },
    async findOne() {
      return null;
    },
    async findMany() {
      return [];
    },
    async count() {
      return 0;
    },
    async update() {
      return null;
    },
    async updateMany() {
      return 0;
    },
    async delete() {},
    async deleteMany() {
      return 0;
    },
    async transaction(callback: (adapter: unknown) => Promise<unknown>) {
      return callback(baseAdapter);
    },
    options: {
      adapterConfig: {
        adapterId: 'kysely',
        adapterName: 'Kysely Adapter',
        supportsBooleans: false,
      },
    },
    ...overrides,
  };

  return baseAdapter as any;
}
